rootProject.name = "giftify"
include("backend:app")
include("backend:member")
include("backend:auth")
include("backend:product")
include("backend:funding")
include("backend:order")
include("backend:payment")
include("backend:notification")
include("backend:search")
include("backend:common")
include("frontend")